---
- name: Add repository 'epel-release'
  yum: name=epel-release state=installed

- name: Add repository 'remi-repo'
  command: rpm -ih http://rpms.famillecollet.com/enterprise/remi-release-7.rpm creates=/etc/yum.repos.d/remi.repo

- name: install php74 and useful packages
  yum: name={{ item }} enablerepo=epel,remi,remi-php74 state=installed
  with_items:
    - php74
    - php74-php-mcrypt
    - php74-php-mbstring
    - php74-php-fpm
    - php74-php-gd
    - php74-php-xml
    - php74-php-pdo
    - php74-php-zip
    - php74-php-intl
    - php74-php-soap
    - php74-php-pdo_mysql
    - php74-php-common
    - php74-php-cli
    - php74-php-curl
    - php74-php-bcmath
    - zip
    - unzip

- name : link env file
  command: ln -s /opt/remi/php74/enable /etc/profile.d/php74.sh creates=/etc/profile.d/php74.sh
  notify: restart php-fpm

- name: Set ownership for php sessions
  file:
    path: "{{ php_fpm_lib_path }}"
    owner: root
    group: "{{ __nginx_user }}"
    recurse: yes


- name: Add php.ini configuration file.
  template:
    src: "php.ini.j2"
    dest: "{{ php_fpm_path }}/php.ini"
    force: yes
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm

- name: Add php-fpm pool configuration file.
  template:
    src: "{{ php_fpm_template }}"
    dest: "{{ php_fpm_pool_path }}/{{ php_fpm_pool_name.split(' ')[0] ~ '.conf' }}"
    force: yes
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm

- name: Create a symbolic link for php
  ansible.builtin.file:
    src: /usr/bin/php74
    dest: /usr/bin/php
    owner: root
    group: root
    state: link