---
dependencies: []

galaxy_info:
  author: Konstantin Palandov
  description: Magento 2 (LEMP with redis) stack setup for CentOS.
  company: "--"
  license: "license (MIT)"
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
      - 6
      - 7
  galaxy_tags:
    - development
    - web